#!/usr/bin/env python2

import rospy
import os
import rospkg

rospy.init_node('PerceptIn_Client')
r = rospkg.RosPack()
path = r.get_path('perceptin_client')

if rospy.has_param('exposition'):
    exposition = rospy.get_param("exposition")
    sentence = path.replace('src','build') + "/perceptin_client " + str(exposition)
else:
    sentence = path.replace('src','build') + "/perceptin_client"

os.system(sentence)
while not rospy.is_shutdown():
    pass