#!/usr/bin/env python2

import rospy
import os
import rospkg

rospy.init_node('PerceptIn_Server')
r = rospkg.RosPack()
path = r.get_path('perceptin_server')

os.system(path.replace('src','build')  +"/perceptin_server")

while not rospy.is_shutdown():
    pass